### PR TITLE
Fixes reported on #15

### PR DESCRIPTION
**Pull request by promatik**
Fixed the issues mentioned on #15:
1) Moved bassets to storage by default
2) Fixed file location and public paths
3) Allowed to set the output as the file path
4) Merged main branch.

### CODE REVIEW

**Comment by tabacitu** [comment]
Thanks @promatik ! I'm still getting the assets localized in bad places though... Look how the assets paths are being created here, see where I added the `dump()`s and `dd()`:
CleanShot 2023-02-07 at 09 31 32@2x


In the end, for me, the first asset gets stored in `storage/bassets/Users/tabacitu/Code/bp-2023-02-02-switch/storage/app/public/bassets/unpkg.com/jquery-ui@1.13.2/dist/jquery-ui.min.js` which is unexpected... what I expected was:

```diff
-storage/bassets/Users/tabacitu/Code/bp-2023-02-02-switch/storage/app/public/bassets/unpkg.com/jquery-ui@1.13.2/dist/jquery-ui.min.js
+storage/app/public/bassets/unpkg.com/jquery-ui@1.13.2/dist/jquery-ui.min.js
```

This seems to be a relative vs absolute path problem. The weird thing is... why are YOU not getting the same problem? Is it a difference between Unix and Windows? Are you able to fix this or should I figure it out?

Thanks!

**Comment by promatik** [comment]
Fixed @tabacitu 👌
The issue was indeed with win/unix filesystem, from now on I'm testing stuff with WSL — Windows Subsystem for Linux 😅

**Comment by tabacitu** [comment]
What do we do about the CSS and JS files we've loaded using `file_get_contents()`? Can't we create a solution for that too, inside Bassets? But... which one?!

CleanShot 2023-02-13 at 21 18 53

**Comment by tabacitu** [comment]
We've decided to do this:

```php
@basset('https://domain.com/operations/reorder.js') // if HTTPS, then internalize
@basset(base_path('resources/operations/reorder.js')) // if absolute path, then internalize
@basset(resource_path('operations/reorder.js')) // if absolute path, then internalize
@basset(public_path('operations/reorder.js')) // if public_path, then do not internalize
@basset('operations/reorder.js') // if simple string, assume it's a public path
```

**Comment by tabacitu** [comment]
Let's also do:
```php
@bassetBlock('unique_name_for_code_block.js')
    <!-- Your JS here -->
@bassetBlock

@bassetBlock('unique_name_for_code_block.css')
    <!-- Your CSS here -->
@endBassetBlock
```

**Pull request merged**
